//! The generated config file, and the report for the terminal.
//!
//! Both read a [`Detected`] and say the same things in two registers: the file
//! documents itself for whoever opens it later, and the report tells the person
//! who ran the command what was found.

use super::{Detected, Generated, Verification};
use std::path::Path;

/// The generated file. `verified` is `None` for the draft that produces it.
pub(super) fn render(d: &Detected, verified: Option<&Verification>) -> String {
    let mut out = String::new();
    out.push_str("# i18n-tasks-rs configuration.\n#\n");
    out.push_str("# Generated by `i18n-tasks-rs init-config` from the layout of this project.\n");
    out.push_str(
        "# This file is plain YAML. It is read, never evaluated: no ERB, no Ruby,\n\
         # no scanner class names. An unknown key is an error.\n#\n",
    );

    out.push_str("# Detected:\n");
    match &d.locale_dir {
        Some(dir) => out.push_str(&format!(
            "#   {dir}: {} locale file(s), {}\n",
            d.files_seen,
            if d.locales.is_empty() {
                "no locale named by any of them".to_string()
            } else {
                format!("locales {}", d.locales.join(", "))
            }
        )),
        None => out.push_str("#   no locale directory\n"),
    }
    match &d.base_locale_from {
        Some(at) => out.push_str(&format!("#   base_locale {} from {at}\n", d.base_locale)),
        None => out.push_str(&format!(
            "#   base_locale {}, assumed: the project's Ruby names no default_locale\n",
            d.base_locale
        )),
    }
    for root in &d.relative_roots_detected {
        out.push_str(&format!(
            "#   relative root {root}: not a default, but it uses relative keys\n"
        ));
    }
    if let Some(v) = verified.filter(|v| v.error.is_none()) {
        out.push_str(&format!(
            "#   read back: {} key(s) in {} locale(s) from {} file(s)\n",
            v.key_count,
            v.locales.len(),
            v.files_read
        ));
    }
    if let Some(gem) = &d.gem_config {
        out.push('#');
        out.push('\n');
        out.push_str(&wrap_comment(&format!(
            "{} is still in the project. `i18n-tasks-rs migrate-config` converts it, and \
             keeps the ignore lists, which this file has none of.",
            gem.display().to_string().replace('\\', "/")
        )));
    }
    if !d.notes.is_empty() {
        out.push_str("#\n# NEEDS ATTENTION:\n");
        for note in &d.notes {
            out.push_str(&wrap_comment(note));
        }
    }

    out.push_str(&format!("\nbase_locale: {}\n", d.base_locale));
    if !d.locales.is_empty() {
        out.push_str(&format!(
            "# locales: [{}]\n\
             # Detected, and left unset on purpose: with no list here the locales come\n\
             # from the files `data.read` matches, so a new one needs no edit.\n",
            d.locales.join(", ")
        ));
    }

    out.push_str("\ndata:\n  read:\n");
    for pattern in &d.read {
        out.push_str(&format!("    - {}\n", quoted(pattern)));
    }
    out.push_str("  # Where a new key goes, and only under `normalize --write`.\n  write:\n");
    out.push_str(&format!("    - {}\n", quoted(&d.write)));
    out.push_str(
        "  # router: conservative_router    # or pattern_router\n\
         \x20 # keep_order: false\n\
         \x20 # external: []                   # read-only data: never missing, never unused\n",
    );

    out.push_str("\nsearch:\n  paths:\n");
    for path in &d.search_paths {
        out.push_str(&format!("    - {path}\n"));
    }
    if d.exclude.is_empty() {
        out.push_str("  # exclude: []\n");
    } else {
        out.push_str("  exclude:\n");
        for path in &d.exclude {
            out.push_str(&format!("    - {path}\n"));
        }
    }
    if d.relative_roots.is_empty() {
        // Not omitted: leaving the key out would restore the gem's five
        // defaults, none of which this project has.
        out.push_str("  relative_roots: []   # no directory here uses relative keys\n");
    } else {
        out.push_str("  relative_roots:\n");
        for root in &d.relative_roots {
            out.push_str(&format!("    - {root}\n"));
        }
    }
    out.push_str(
        "  # only: []\n\
         \x20 # relative_exclude_method_name_paths: []\n",
    );

    out.push_str(
        "\n# Nothing is ignored yet. Each list takes key patterns — `devise.*`,\n\
         # `{a,b}.*`, `a.*.b` — and `ignore` applies to every check at once.\n\
         #\n\
         # ignore: []\n\
         # ignore_missing: []\n\
         # ignore_unused: []\n\
         # ignore_eq_base: []\n\
         # ignore_inconsistent_interpolations: []\n",
    );
    out
}

/// A `data` path is quoted when YAML would read it as anything but a string.
fn quoted(path: &str) -> String {
    if path.starts_with([
        '*', '&', '{', '[', '"', '\'', '%', '@', '`', '!', '|', '>', '#',
    ]) || path.contains(": ")
    {
        format!("\"{}\"", path.replace('\\', "\\\\").replace('"', "\\\""))
    } else {
        path.to_string()
    }
}

/// One note, wrapped into comment lines that stay inside 80 columns.
fn wrap_comment(note: &str) -> String {
    let mut out = String::new();
    let mut line = String::from("#   ");
    for word in note.split_whitespace() {
        if line.len() + 1 + word.len() > 79 && line.len() > 4 {
            out.push_str(line.trim_end());
            out.push('\n');
            line = String::from("#     ");
        }
        line.push_str(word);
        line.push(' ');
    }
    out.push_str(line.trim_end());
    out.push('\n');
    out
}

/// The report for the terminal.
pub fn to_text(g: &Generated, to: &Path, written: bool) -> String {
    let d = &g.detected;
    let mut s = String::new();
    s.push_str(&format!(
        "{} -> {}\n",
        d.locale_dir.clone().unwrap_or_else(|| "(no data)".into()),
        to.display()
    ));
    s.push_str(&format!(
        "  data.read: {} pattern(s) covering {} locale file(s)\n",
        d.read.len(),
        d.files_seen
    ));
    s.push_str(&format!("  data.write: {}\n", d.write));
    match &d.base_locale_from {
        Some(at) => s.push_str(&format!("  base_locale: {} from {at}\n", d.base_locale)),
        None => s.push_str(&format!("  base_locale: {}, assumed\n", d.base_locale)),
    }
    s.push_str(&format!("  search.paths: {}\n", d.search_paths.join(", ")));
    s.push_str(&format!(
        "  search.relative_roots: {}{}\n",
        if d.relative_roots.is_empty() {
            "none".into()
        } else {
            d.relative_roots.join(", ")
        },
        if d.relative_roots_detected.is_empty() {
            String::new()
        } else {
            format!(" ({} detected)", d.relative_roots_detected.join(", "))
        }
    ));
    if g.verified.error.is_none() {
        s.push_str(&format!(
            "  read back: {} key(s) in {} locale(s) from {} file(s)\n",
            g.verified.key_count,
            g.verified.locales.len(),
            g.verified.files_read
        ));
    }
    if let Some(gem) = &d.gem_config {
        s.push_str(&format!(
            "  NOTE {} exists. `migrate-config` converts it and keeps the ignore lists.\n",
            gem.display()
        ));
    }
    for note in &d.notes {
        s.push_str(&format!("  NEEDS ATTENTION: {note}\n"));
    }
    if written {
        s.push_str(&format!("  wrote {}\n", to.display()));
    } else {
        s.push_str("  nothing written. Pass `--write` to create the file.\n");
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A note is the only free text in the generated file, so the wrap is the
    /// only thing keeping the header inside 80 columns. Every line has to stay
    /// a comment, too: a wrapped line that lost its `#` is a config the tool
    /// then refuses to read.
    #[test]
    fn a_note_wraps_into_comment_lines_that_stay_in_80_columns() {
        let note = "no locale files under config/locales, locales, app/locales. \
                    `data.read` below is the gem's default; point it at the real data.";
        let wrapped = wrap_comment(note);
        assert!(wrapped.ends_with('\n'));
        let lines: Vec<&str> = wrapped.trim_end().lines().collect();
        assert!(lines.len() > 1, "{wrapped}");
        for line in &lines {
            assert!(line.starts_with('#'), "{line:?}");
            assert!(line.len() < 80, "{} columns: {line:?}", line.len());
        }
        assert!(lines[0].starts_with("#   "), "{:?}", lines[0]);
        for line in &lines[1..] {
            assert!(line.starts_with("#     "), "{line:?}");
        }
        // Every word survives, in order, and none is split.
        let back: Vec<&str> = lines
            .iter()
            .flat_map(|l| l.trim_start_matches('#').split_whitespace())
            .collect();
        assert_eq!(back, note.split_whitespace().collect::<Vec<&str>>());
        // A single short note is one line, not two.
        assert_eq!(wrap_comment("short enough"), "#   short enough\n");
    }

    /// Every generated path starts with the locale directory, so none of them
    /// needs quoting. The rule is here for the one that would: a `data.read`
    /// beginning with `*` is a YAML alias.
    #[test]
    fn a_path_is_quoted_only_when_yaml_needs_it() {
        for plain in [
            "config/locales/%{locale}.yml",
            "config/locales/*.%{locale}.yml",
            "config/locales/%{locale}/**/*.yml",
        ] {
            assert_eq!(quoted(plain), plain);
        }
        assert_eq!(quoted("*.%{locale}.yml"), "\"*.%{locale}.yml\"");
    }
}
